enabled: true
about_label: About Ramesh
about_header: 'Photography is the beauty of Life Captured.'
about_content: 'Profession: Software Engineering.
Passion: Photography
Loves to shoot Wildlife, Landscapes, Portaits, Creative and Candid.'
copyright: '&copy; Ramesh Yoha | &copy; Dreamographers'
social_networks:
  -
    icon: fa-twitter
    label: Twitter
    url: 'https://twitter.com/RameshYoha'
  -
    icon: fa-instagram
    label: Instagram
    url: 'https://www.instagram.com/yrameshk/'
  -
    icon: fa-youtube
    label: YouTube
    url: 'https://www.youtube.com/channel/UCwGH1NcE7D4LNV2NHDnBNrg'
  -
    icon: fa-linkedin
    label: LinkedIn
    url: 'https://www.linkedin.com/in/ramesh-yoha/'
  -
    icon: fa-facebook
    label: Facebook
    url: 'https://www.facebook.com/Ramesh.K.Yoha'
contact_header: 'Get in touch'
social_header: 'Follow me on ...'
favicon: favicon.png
